# Generated by Django 3.1.1 on 2020-09-23 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('ID', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('VER', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=255)),
                ('ADDRESS', models.CharField(max_length=500)),
                ('LONG', models.FloatField(default=0.0)),
                ('LAT', models.FloatField(default=0.0)),
                ('TYPE', models.CharField(choices=[('mem', 'Member'), ('loc', 'Location')], default='mem', max_length=3)),
                ('ROOM_INSTANCE', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='database.room')),
            ],
        ),
    ]
