# Generated by Django 3.1.1 on 2020-09-23 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='VER',
            new_name='VER_LOC',
        ),
        migrations.AddField(
            model_name='room',
            name='VER_MEM',
            field=models.IntegerField(default=0),
        ),
    ]
